#include <stdio.h>
#include <string.h>
#include <ctype.h>
#include <stdlib.h>
#include "check.h"
#include "lexic.h"

int check_tokens(lexer_t* lexer)
{
    int error_found = 0;   // error flag to track whether any errro is found

    // Looping through all tokens generated by the lexer
    for(int i = 0; i < lexer -> token_count; i++)
    {
        int line = lexer -> tokens[i].line_no;     // getting line number of token

        // check token type
        switch(lexer -> tokens[i].type)
        { 
            // Validate preprocessor directive
            case TOKEN_PREPROCESSOR:
                if(validate_preprocessor(lexer, i) == LEX_FAILURE)
                    error_found = 1;
                break;

                // Validate numbers
            case TOKEN_NUMBER_DECIMAL:
            case TOKEN_NUMBER_FLOAT:
            case TOKEN_NUMBER_BINARY:
            case TOKEN_NUMBER_OCTAL:
            case TOKEN_NUMBER_HEXA:
                if(validate_numbers(lexer, i) == LEX_FAILURE)
                    error_found = 1;
                break;
            
            case TOKEN_UNTERMINATED_STRING:
               printf("%s:%d:%d: " RED "error: " RESET "missing terminating \" character\n", lexer->filename, line, lexer->tokens[i].col_no);
                break;
            
            case TOKEN_UNTERMINATED_CHAR:
                printf("%s:%d:%d: " RED "error: " RESET "missing terminating ' character\n", lexer->filename, line, lexer->tokens[i].col_no);
                break;

            case TOKEN_UNKNOWN:
                printf("%s:%d:%d: " RED "error: " RESET "unknown token '%s'\n", lexer->filename, line, lexer->tokens[i].col_no, lexer->tokens[i].value);  
                error_found = 1;
                break;
            
            default:
                break;
        }
    }

    check_brackets(lexer, &error_found);
    check_missing_semicolon(lexer, &error_found);

    return error_found;;
}
      
lex_status_t validate_preprocessor(lexer_t* lexer, int index)
{
    char* directives[] = {"include", "define", "undef", "ifdef", "ifndef", "endif", "if", "elif", "else", "pragma", NULL};
    char *line = lexer -> tokens[index].value;   // token value

    int i = 0, j = 0;
    char buffer[32];

    // First character must be '#'
    if(line[i++] != '#')
        return LEX_FAILURE;

    // skipping whitespaces and tab
    while(line[i] == ' ' || line[i] == '\t')
        i++;

    // If nothing afte '#'
    if(line[i] == '\0')
    {
        printf("%s:%d:%d: " RED "error: " RESET "missing preprocessor directive name\n", lexer->filename, lexer->tokens[index].line_no, lexer->tokens[index].col_no);
        return LEX_FAILURE;
    }

    // Extracting directive word
    while(isalpha(line[i]))
        buffer[j++] = line[i++];
    
    buffer[j] = '\0';

    // Check if directive is valid
    for(int k = 0; directives[k] != NULL; k++)
    {
        if(strcmp(directives[k], buffer) == 0)
            return LEX_SUCCESS; 
    }

    // Invalid directive
    printf("%s:%d:%d: " RED "error: " RESET "invalid preprocessor directive '#%s'\n",lexer->filename,lexer->tokens[index].line_no,lexer->tokens[index].col_no,buffer);

    return LEX_FAILURE;
}

lex_status_t validate_numbers(lexer_t* lexer, int index)
{
    int type = lexer->tokens[index].type;
    char* value = lexer->tokens[index].value;
    int line = lexer->tokens[index].line_no;
    int i = 0;
    
    // decimal validation
    if(type == TOKEN_NUMBER_DECIMAL)
    {
        // Check if all characters are digits
        while(value[i] != '\0')
        {
            if(!isdigit(value[i++]))
            {
               printf("%s:%d:%d: " RED "error: " RESET "invalid decimal constant '%s'\n",lexer->filename,lexer->tokens[index].line_no,lexer->tokens[index].col_no,value);
            }
        }
    }
    // Binary validation
    else if(type == TOKEN_NUMBER_BINARY)
    {
        // binary must have digits after 0b
        if(value[2] == '\0')
        {
           printf("%s:%d:%d: " RED "error: " RESET "invalid binary digit '%c'\n", lexer->filename, line, lexer->tokens[index].col_no, value[i]);
        }

        for(i = 2; value[i] != '\0'; i++) 
        {
            // binary only allows 0 or 1
            if(value[i] != '0' && value[i] != '1') 
            {
                printf("%s:%d:%d: " RED "error: " RESET "invalid binary digit '%c'\n",lexer->filename,line,lexer->tokens[index].col_no, value[i]);
                return LEX_FAILURE;
            }
        }
    }
    // Octal validation
    else if(type == TOKEN_NUMBER_OCTAL) 
    {
        for(i = 1; value[i] != '\0'; i++) 
        {
            // octal digits must be 0 - 7 
            if(value[i] < '0' || value[i] > '7') 
            {
               printf("%s:%d:%d: " RED "error: " RESET "invalid octal digit '%c'\n",lexer->filename,line,lexer->tokens[index].col_no, value[i]);
                return LEX_FAILURE;
            }
        }
    }
    // Hexa decimal validation 
    else if(type == TOKEN_NUMBER_HEXA) 
    {
        //  must contain digits after 0x
        if(value[2] == '\0') 
        { 
           printf("%s:%d:%d: " RED "error: " RESET "invalid hex digit '%c'\n",lexer->filename,line,lexer->tokens[index].col_no,value[i]);
            return LEX_FAILURE; 
        }

        for(i = 2; value[i] != '\0'; i++) 
        {
            if(!isxdigit(value[i])) 
            {
               printf("%s:%d:%d: " RED "error: " RESET "invalid hex digit '%c'\n",lexer->filename,line,lexer->tokens[index].col_no,value[i]);
            }
        }
    }
    // FLoat validation
    else if(type == TOKEN_NUMBER_FLOAT) 
    {
        int dot_count = 0, suffix_count = 0, len = strlen(value);

        for(i = 0; i < len; i++) 
        {
            if(value[i] == '.') 
                dot_count++;

            else if(isalpha(value[i])) 
            {
                // Valid float suffix
                if(strchr("fFlL", value[i])) 
                {
                    suffix_count++;

                    // checking suffix is at end or not
                    if(i != len - 1) 
                    { 
                        printf("%s:%d:%d: " RED "error: " RESET "invalid suffix '%s'\n",lexer->filename,line,lexer->tokens[index].col_no,value);
                        return LEX_FAILURE; 
                    }
                } 
                else 
                {
                   printf("%s:%d:%d: " RED "error: " RESET "invalid suffix '%s'\n",lexer->filename, line, lexer->tokens[index].col_no,value);
                    return LEX_FAILURE;
                }
            }
        }
        // checking count of dot and suffix
        if(dot_count > 1 || suffix_count > 1) 
        {
            printf("%s:%d:%d: " RED "error: " RESET "invalid float '%s'\n",lexer->filename,line,lexer->tokens[index].col_no, value);
            return LEX_FAILURE;
        }
    }
    return LEX_SUCCESS;
}


void check_brackets(lexer_t *lexer, int *error_found)
{
    char stack[100];      // stack for brackets
    int top = -1;

    for(int i = 0; i < lexer->token_count; i++)
    {
        // skipping non - punctuators
        if(lexer->tokens[i].type != TOKEN_PUNCTUATOR)
            continue;

        char ch = lexer->tokens[i].value[0];
        int line = lexer->tokens[i].line_no;

        // Opening brackets
        if(ch == '(' || ch == '{' || ch == '[')
        {
            stack[++top] = ch;                   // push to stack
        }
        // closing brackets
        else if(ch == ')' || ch == '}' || ch == ']')
        {
            if(top < 0)
            {
                printf("%s:%d:%d: " RED "error: " RESET "extra '%c'\n", lexer->filename, line, lexer->tokens[i].col_no, ch);
                *error_found = 1;
            }
            else
            {
                char open = stack[top--];
                // check matching
                if((open == '(' && ch != ')') || (open == '{' && ch != '}') || (open == '[' && ch != ']'))
                {
                    printf("%s:%d:%d: " RED "error: " RESET "mismatched '%c' and '%c'\n", lexer->filename, line, lexer->tokens[i].col_no, open,ch);
                    *error_found = 1;
                }
            }
        }
    }

    // Unclosed bracket
    if(top >= 0)
    {
        printf("%s:%d:%d: " RED "error: " RESET "unclosed bracket '%c'\n",lexer->filename,lexer->tokens[lexer->token_count - 1].line_no,lexer->tokens[lexer->token_count - 1].col_no, stack[top]);
        *error_found = 1;
    }
}

void check_missing_semicolon(lexer_t *lexer, int* error_found)
{
    // checking if there are tokens or not
    if (lexer->token_count == 0) 
        return;
    
    // storing the token
    int current_line = lexer->tokens[0].line_no;
    char last_token[MAX_TOKEN_LEN] = "";     
    token_type_t last_type = TOKEN_UNKNOWN;
    int skip_line = 0;                      // flag to skip checking a line if it already contains an error
    
    // Looping through all the tokens
    for(int i = 0; i <= lexer->token_count; i++)
    {
        // Check if the line has changed OR if we reached the end of tokens
        if(i < lexer->token_count && lexer->tokens[i].line_no != current_line || i == lexer->token_count)
        {
            // If the line should not be skipped and last token is valid
            if(!skip_line && last_token[0] != '\0' &&
               strcmp(last_token, ";") != 0 && strcmp(last_token, "{") != 0 &&
               strcmp(last_token, "}") != 0 && strcmp(last_token, ")") != 0 &&
               !is_control_keyword(last_token) &&                               // ignoring control statements like if for while also braces and closing paranthesis
               last_type != TOKEN_OPERATOR)                                     // ignore if line ends with operator
            {
                printf("%s:%d:%d: " RED "error: " RESET "missing semicolon\n",lexer->filename,current_line,lexer->tokens[i-1].col_no);
                *error_found = 1;
            }

            if(i == lexer->token_count) 
                break;

            current_line = lexer->tokens[i].line_no;
            last_token[0] = '\0';                      // Reset last token for the new line
            skip_line = 0;                             // Reset skip flag
        }

        // If the line contains an error, skip semicolon checking
        if(lexer->tokens[i].type == TOKEN_PREPROCESSOR || 
           lexer->tokens[i].type == TOKEN_UNKNOWN || 
           lexer->tokens[i].type == TOKEN_UNTERMINATED_STRING || 
           lexer->tokens[i].type == TOKEN_UNTERMINATED_CHAR) 
        {
            skip_line = 1;
        } 
        else 
        {
            // store the current token as the last token of the line and storing its token type
            strcpy(last_token, lexer->tokens[i].value);
            last_type = lexer->tokens[i].type;
        }
    }
}

int is_control_keyword(const char *token)
{
    return (strcmp(token, "if") == 0 || strcmp(token, "else") == 0 ||
            strcmp(token, "for") == 0 || strcmp(token, "while") == 0 ||
            strcmp(token, "switch") == 0 || strcmp(token, "do") == 0);
}